site_name: Auxiliary Engineering Playbook
site_author: Jonathan Biddle <jbiddle@wayfair.com>
docs_dir: markdown
site_dir: docs

nav:

  - Overview: index.md
  - Goals:
    - Accelerated Diffusion: goals/diffusion.md
    - Guide Platform Efforts: goals/platforms.md
    - Mobility: goals/mobility.md
    - Career Tracks: goals/careers.md
  - Running Engagements:
    - Overview: running_engagements/overview.md
    - Roles: running_engagements/roles.md
    - Sourcing: running_engagements/sourcing.md
    - Planning: running_engagements/planning.md
    - Setting Expectations: running_engagements/expectations.md
    - Kick-off: running_engagements/kickoff.md
    - Iterating: running_engagements/iterating.md
    - Wrapping up: running_engagements/wrapping_up.md
    - Following up: running_engagements/following_up.md
    - What's next: running_engagements/whats_next.md
  - Theory:
    - Concepts: theory/concepts.md
    - Elements: theory/elements.md
    - Failure Modes: theory/failure_modes.md
    - Marketing: theory/marketing.md
  - Example Engagements:
    - Overview: example_engagement/overview.md

theme:
  name: material

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
  - markdown_include.include:
      base_path: markdown